version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=cybersmart_db
      - POSTGRES_USER=cybersmart_dbuser
      - POSTGRES_PASSWORD=arobustpassword
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/src
    ports:
      - "8080:8080"
      - "5678:5678"
    depends_on:
      - db