# Generated by Django 3.2.3 on 2021-05-15 10:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('bg_colour', models.CharField(choices=[('CD', '#0000FF'), ('WM', '#FFA500'), ('HT', '#FF0000'), ('DT', '#FFFFFF')], default='DT', max_length=2)),
                ('task_done', models.BooleanField(default=False)),
                ('created', models.DateField(default=django.utils.timezone.now)),
                ('todolist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='todolistapp.todolist')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
