# Generated by Django 3.2.3 on 2021-05-15 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolistapp', '0002_task_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
